// file: SubastaOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologia;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: SubastaOntology.java
 * @author OntologyBeanGenerator v4.1
 * @version 2021/05/10, 18:20:01
 */
public class SubastaOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = -5916493442331476618L;

  //NAME
  public static final String ONTOLOGY_NAME = "Subasta";
  // The singleton instance of this ontology
  private static Ontology theInstance = new SubastaOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String OFERTAR_OFERTA="oferta";
    public static final String OFERTAR="Ofertar";
    public static final String OFERTA_PREZO="prezo";
    public static final String OFERTA_TITULO="titulo";
    public static final String OFERTA="Oferta";

  /**
   * Constructor
  */
  private SubastaOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema ofertaSchema = new ConceptSchema(OFERTA);
    add(ofertaSchema, ontologia.Oferta.class);
    add(ofertaSchema, ontologia.impl.DefaultOferta.class);


        // adding AgentAction(s)
    AgentActionSchema ofertarSchema = new AgentActionSchema(OFERTAR);
    add(ofertarSchema, ontologia.Ofertar.class);
    add(ofertarSchema, ontologia.impl.DefaultOfertar.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    ofertaSchema.add(OFERTA_TITULO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    ofertaSchema.add(OFERTA_PREZO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    ofertarSchema.add(OFERTAR_OFERTA, ofertaSchema, ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
