// file: SubastaOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologia;

import jade.content.onto.*;
import jade.content.schema.*;
import ontologia.impl.*;

/** file: SubastaOntology.java
 * @author OntologyBeanGenerator v4.1
 * @version 2021/05/11, 12:30:11
 */
public class SubastaOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 8268541762640966406L;

  //NAME
  public static final String ONTOLOGY_NAME = "Subasta";
  // The singleton instance of this ontology
  private static Ontology theInstance = new SubastaOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String PROPONER_PROPOSTAOFERTA="propostaOferta";
    public static final String PROPONER="Proponer";
    public static final String OFERTAR_OFERTAENVIAR="ofertaEnviar";
    public static final String OFERTAR="Ofertar";
    public static final String INFORMARVICTORIA_OFERTAGANADORA="ofertaGanadora";
    public static final String INFORMARVICTORIA_AGENTEGANADOR="agenteGanador";
    public static final String INFORMARVICTORIA="InformarVictoria";
    public static final String INFORMARRONDA_GANADORRONDA="ganadorRonda";
    public static final String INFORMARRONDA_OFERTAGANADORARONDA="ofertaGanadoraRonda";
    public static final String INFORMARRONDA="InformarRonda";
    public static final String OFERTA_PREZO="prezo";
    public static final String OFERTA_TITULO="titulo";
    public static final String OFERTA="Oferta";

  /**
   * Constructor
  */
  private SubastaOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema ofertaSchema = new ConceptSchema(OFERTA);
    add(ofertaSchema, Oferta.class);

    // adding AgentAction(s)
    AgentActionSchema informarRondaSchema = new AgentActionSchema(INFORMARRONDA);
    add(informarRondaSchema, InformarRonda.class);
    AgentActionSchema informarVictoriaSchema = new AgentActionSchema(INFORMARVICTORIA);
    add(informarVictoriaSchema, InformarVictoria.class);
    AgentActionSchema ofertarSchema = new AgentActionSchema(OFERTAR);
    add(ofertarSchema, Ofertar.class);
    AgentActionSchema proponerSchema = new AgentActionSchema(PROPONER);
    add(proponerSchema, Proponer.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    ofertaSchema.add(OFERTA_TITULO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    ofertaSchema.add(OFERTA_PREZO, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    informarRondaSchema.add(INFORMARRONDA_OFERTAGANADORARONDA, ofertaSchema, ObjectSchema.MANDATORY);
    informarRondaSchema.add(INFORMARRONDA_GANADORRONDA, (ConceptSchema)getSchema(BasicOntology.AID), ObjectSchema.MANDATORY);
    informarVictoriaSchema.add(INFORMARVICTORIA_AGENTEGANADOR, (ConceptSchema)getSchema(BasicOntology.AID), ObjectSchema.MANDATORY);
    informarVictoriaSchema.add(INFORMARVICTORIA_OFERTAGANADORA, ofertaSchema, ObjectSchema.MANDATORY);
    ofertarSchema.add(OFERTAR_OFERTAENVIAR, ofertaSchema, ObjectSchema.MANDATORY);
    proponerSchema.add(PROPONER_PROPOSTAOFERTA, ofertaSchema, ObjectSchema.MANDATORY);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
